const C=window.ALIMENTA_CONFIG;const $=id=>document.getElementById(id);const days=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];
const allergens={gluten:'Glutine',milk:'Latte',eggs:'Uova',fish:'Pesce',shellfish:'Crostacei',molluscs:'Molluschi',peanuts:'Arachidi',nuts:'Frutta a guscio',soy:'Soia',sesame:'Sesamo',celery:'Sedano',mustard:'Senape',lupin:'Lupini',sulphites:'Solfiti'};
const ingredients={oats:'Avena',rice:'Riso',pasta:'Pasta',bread:'Pane',potato:'Patate',corn:'Mais',beans:'Fagioli',lentils:'Lenticchie',chickpeas:'Ceci',tofu:'Tofu',egg:'Uova',chicken:'Pollo',fish:'Pesce',yogurt:'Yogurt',soyYogurt:'Yogurt di soia',almonds:'Mandorle',peanut:'Arachidi',fruit:'Frutta',zucchini:'Zucchine',carrot:'Carote',tomato:'Pomodoro',spinach:'Spinaci',oliveOil:'Olio d’oliva'};
let session=null,state={profile:null,plan:null,messages:[]},mode='login',chosen=(new Date().getDay()+6)%7,busy=false,pendingChat=null;
function secureUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
const configured=()=>C.authEnabled===true&&location.protocol==='https:'&&secureUrl(C.supabaseUrl)&&C.supabasePublishableKey&&secureUrl(C.apiUrl);
if(location.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(location.hostname))location.replace('https://'+location.host+location.pathname+location.search+location.hash);
function say(text){$('status').textContent=text;}
function show(id){['auth','profile','ideas','chat','recovery'].forEach(x=>$(x).hidden=x!==id);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo(0,0);}
async function request(url,options={}){if(location.protocol!=='https:'||!secureUrl(url))throw Error('Accesso consentito solo tramite HTTPS.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const r=await fetch(url,{...options,signal:controller.signal});let data;try{data=await r.json();}catch{throw Error('Il servizio non ha risposto correttamente.');}if(!r.ok)throw Error(data.error_description||data.msg||data.error||'Richiesta non riuscita.');return data;}catch(e){if(e.name==='AbortError')throw Error('La risposta sta impiegando troppo tempo. Riprova tra poco.');if(e instanceof TypeError)throw Error('Connessione non disponibile. Controlla Internet e riprova.');throw e;}finally{clearTimeout(timer);}}
async function auth(path,body,method='POST'){return request(C.supabaseUrl+'/auth/v1/'+path,{method,headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{})},...(body?{body:JSON.stringify(body)}:{})});}
function saveSession(s){session=s;try{sessionStorage.setItem('alimenta-session',JSON.stringify(s));}catch{}}
async function api(path,body,method=body?'POST':'GET'){if(!session)throw Error('Accedi per continuare.');if(session.expires_at&&session.expires_at<Date.now()/1000+60){const renewed=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});saveSession({...renewed,expires_at:Date.now()/1000+renewed.expires_in});}return request(C.apiUrl.replace(/\/$/,'')+path,{method,headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button[type="submit"],form .primary,#generate').forEach(b=>b.disabled=true);say('Un momento…');try{await fn();}catch(e){say(e.message);}finally{busy=false;document.querySelectorAll('button[type="submit"],form .primary,#generate').forEach(b=>b.disabled=false);}}
function checks(id,values,name){for(const [value,label]of Object.entries(values)){const l=document.createElement('label');l.className='check';const i=document.createElement('input');i.type='checkbox';i.name=name;i.value=value;l.append(i,document.createTextNode(label));$(id).append(l);}}
checks('allergies',allergens,'allergies');checks('dislikes',ingredients,'dislikes');
function trainingRows(){for(let i=0;i<7;i++){const row=document.createElement('div');row.className='training-row';const label=document.createElement('label');label.className='check';const active=document.createElement('input');active.type='checkbox';active.name='training_'+i+'_enabled';label.append(active,document.createTextNode(days[i]));row.append(label);for(const [suffix,title]of [['start','Inizio'],['end','Fine (facoltativa)']]){const l=document.createElement('label');l.textContent=title;const input=document.createElement('input');input.type='time';input.name='training_'+i+'_'+suffix;input.disabled=true;l.append(input);row.append(l);}const l=document.createElement('label');l.textContent='Cena';const select=document.createElement('select');select.name='training_'+i+'_dinner';select.disabled=true;for(const [value,title]of [['auto','Proponi tu'],['before','Prima'],['after','Dopo']]){const option=document.createElement('option');option.value=value;option.textContent=title;select.append(option);}l.append(select);row.append(l);active.onchange=()=>row.querySelectorAll('input[type=time],select').forEach(x=>x.disabled=!active.checked);$('trainingRows').append(row);}}
trainingRows();
function fillProfile(){const p=state.profile?.profile;if(!p)return;for(let i=0;i<7;i++){const row=$('profileForm').elements;const t=p.training?.find(t=>t.day===i);row['training_'+i+'_enabled'].checked=!!t;for(const suffix of ['start','end','dinner']){row['training_'+i+'_'+suffix].disabled=!t;row['training_'+i+'_'+suffix].value=t?.[suffix]||(suffix==='dinner'?'auto':'');}}for(const [key,value]of Object.entries(p)){const el=$('profileForm').elements.namedItem(key);if(!el)continue;if(['allergies','dislikes','excludedGroups'].includes(key)){document.querySelectorAll(`[name="${key}"]`).forEach(x=>x.checked=value.includes(x.value));}else if(key==='consent')el.checked=value;else el.value=value;}ageRule();}
function ageRule(){const f=$('profileForm');const age=Number(f.elements.age.value);for(const value of ['weight','muscle'])f.elements.goal.querySelector('[value="'+value+'"]').disabled=age<18;if(age<18&&['weight','muscle'].includes(f.elements.goal.value))f.elements.goal.value='balance';}
$('profileForm').elements.age.addEventListener('input',ageRule);
function bubble(text,role){const p=document.createElement('p');p.className='bubble '+role;p.textContent=text;$('messages').append(p);return p;}
function renderMessages(){$('olderMessages').hidden=state.messages.length<20||!state.messages[0]?.created_at;$('messages').replaceChildren();for(const m of state.messages)bubble(m.content,m.role);if(!state.messages.length)bubble('Dimmi cosa vuoi cambiare: ti propongo opzioni concrete compatibili con il tuo profilo.','assistant');}
function renderPlan(){$('days').innerHTML=days.map((d,i)=>`<button data-day="${i}" class="${i===chosen?'selected':''}" aria-pressed="${i===chosen}">${d.slice(0,3)}</button>`).join('');$('meals').replaceChildren();const record=state.plan;const stale=record&&(record.profile_revision!==state.profile?.revision||record.plan.version!==2);$('planState').textContent=stale?'Il profilo è cambiato. Rigenera le proposte prima di usarle.':record?days[chosen]:'Il tuo profilo è pronto. Prepara le prime idee per i pasti.';$('generate').textContent=record?'Rigenera le mie idee':'Prepara le mie idee per i pasti';if(!record||stale)return;const plan=record.plan;const notice=document.createElement('p');notice.className='note';notice.textContent=plan.notice;$('meals').append(notice);for(const text of [plan.fruitNote,plan.days[chosen].trainingNote])if(text){const note=document.createElement('p');note.className='note';note.textContent=text;$('meals').append(note);}plan.days[chosen].meals.forEach((m,i)=>{const card=document.createElement('details');card.className='meal';card.open=i===0;const summary=document.createElement('summary');const name=document.createElement('div');name.className='meal-name';const label=document.createElement('p');label.textContent=(plan.version===2?['Colazione','Spuntino mattina','Pranzo','Merenda','Cena']:['Colazione','Pranzo','Cena'])[i]+(m.timing?' · '+m.timing:'');const title=document.createElement('h3');title.textContent=m.title;name.append(label,title);summary.append(name);const content=document.createElement('div');content.className='content';const list=document.createElement('ul');m.items.forEach(item=>{const li=document.createElement('li');li.textContent=item.label+(item.portion?' · riferimento standard: '+item.portion:'');list.append(li);});const prep=document.createElement('p');prep.className='note';prep.textContent=m.preparation;content.append(list,prep);card.append(summary,content);$('meals').append(card);});const source=document.createElement('a');source.href=plan.portionSource;source.target='_blank';source.rel='noopener';source.textContent='Fonte delle porzioni standard: CREA';source.className='small';$('meals').append(source);}
function renderOverview(){const box=$('overviewBody');box.replaceChildren();const o=state.overview;if(!o)return;const text=value=>{const el=document.createElement('p');el.className='small';el.textContent=value;box.append(el);};if(o.energy)text('Dispendio giornaliero stimato: circa '+o.energy.low+'–'+o.energy.high+' kcal. Non è un obiettivo prescritto.');text(o.explanation);if(o.macros)text('Riferimenti generali: carboidrati 45–60% dell’energia; grassi 20–35%. Proteine: circa '+o.macros.proteinReference+' g/die come riferimento per adulti sani (0,83 g/kg), non come target sportivo. Questi riferimenti non rappresentano i macro del menu.');text(o.food);if(o.training.entries.length)text('Sport: '+o.training.entries.map(t=>days[t.day]+' '+t.start+(t.end?'–'+t.end:' (fine da indicare)')+' · cena '+({auto:'da proporre',before:'prima',after:'dopo'}[t.dinner])).join('; ')+(o.training.source==='text'?'. Orari interpretati dal testo, da confermare nel Profilo.':''));else if(state.profile?.profile.sport)text('Non abbiamo orari completi per lo sport: conferma giorni e orari nel Profilo per collegare la cena all’allenamento.');if(o.training.uncertain)text('Una parte degli orari scritti non è chiara: verifica i campi di allenamento.');const review=document.createElement('label');review.className='check';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.id='reviewExplanation';review.append(checkbox,document.createTextNode('Ho letto: stime e quantità sono orientative, il menu non è conteggiato per raggiungerle.'));box.append(review);for(const source of o.sources){const link=document.createElement('a');link.href=source.url;link.target='_blank';link.rel='noopener';link.textContent=source.label;link.className='source-link';box.append(link);}}
async function load(){state=await api('/state');$('nav').hidden=!state.profile;$('logout').hidden=false;fillProfile();renderOverview();renderPlan();renderMessages();show(state.profile?'ideas':'profile');say('');}
function setMode(next){if(next==='signup'&&C.registrationEnabled!==true){say('Registrazioni pubbliche non ancora aperte.');return;}mode=next;$('ageConsent').hidden=mode!=='signup';$('authForm').elements.eligible.required=mode==='signup';$('authSubmit').textContent=mode==='signup'?'Crea account':'Accedi';$('authForm').elements.password.autocomplete=mode==='signup'?'new-password':'current-password';$('loginMode').classList.toggle('active',mode==='login');$('signupMode').classList.toggle('active',mode==='signup');}
$('loginMode').onclick=()=>setMode('login');$('signupMode').onclick=()=>setMode('signup');
$('authForm').onsubmit=e=>{e.preventDefault();run(async()=>{if(!configured())throw Error('Registrazione non ancora attiva: il progetto deve essere collegato ai servizi.');if(mode==='signup'&&C.registrationEnabled!==true)throw Error('Registrazioni pubbliche non ancora aperte.');const f=e.target.elements;const payload={email:f.email.value.trim(),password:f.password.value};f.password.value='';if(mode==='signup'){await auth('signup?redirect_to='+encodeURIComponent(location.origin+location.pathname),payload);f.password.value='';say('Controlla la tua email per confermare la registrazione. Poi torna qui e accedi.');return;}const s=await auth('token?grant_type=password',payload);saveSession({...s,expires_at:Date.now()/1000+s.expires_in});f.password.value='';await load();});};
$('google').onclick=()=>{if(!configured()||C.googleEnabled!==true){say('Accesso Google non ancora configurato.');return;}const url=new URL(C.supabaseUrl+'/auth/v1/authorize');url.searchParams.set('provider','google');url.searchParams.set('redirect_to',location.origin+location.pathname);location.assign(url.href);};
$('forgot').onclick=()=>run(async()=>{if(!configured())throw Error('Servizio non ancora configurato.');const email=$('authForm').elements.email.value.trim();if(!email)throw Error('Inserisci prima la tua email.');await auth('recover?redirect_to='+encodeURIComponent(location.origin+location.pathname),{email});say('Se l’indirizzo è registrato, riceverai un link per scegliere una nuova password.');});
$('recoveryForm').onsubmit=e=>{e.preventDefault();run(async()=>{const password=e.target.elements.password.value;e.target.elements.password.value='';await auth('user',{password},'PUT');e.target.reset();await load();say('Password aggiornata.');});};
$('logout').onclick=()=>run(async()=>{try{await auth('logout',{});}finally{session=null;sessionStorage.removeItem('alimenta-session');state={profile:null,plan:null,messages:[]};$('nav').hidden=true;$('logout').hidden=true;$('profileForm').reset();$('messages').replaceChildren();$('meals').replaceChildren();show('auth');say('Hai effettuato l’uscita.');}});
$('profileForm').onsubmit=e=>{e.preventDefault();run(async()=>{const fd=new FormData(e.target);const p=Object.fromEntries(fd);for(const k of ['age','weight','height'])p[k]=Number(p[k]);p.allergies=fd.getAll('allergies');p.dislikes=fd.getAll('dislikes');p.excludedGroups=fd.getAll('excludedGroups');p.consent=fd.get('consent')==='on';p.training=[];for(let i=0;i<7;i++)if(fd.get('training_'+i+'_enabled')==='on')p.training.push({day:i,start:fd.get('training_'+i+'_start')||'',end:fd.get('training_'+i+'_end')||'',dinner:fd.get('training_'+i+'_dinner')||'auto'});for(const k of Object.keys(p))if(k.startsWith('training_'))delete p[k];await api('/profile',p,'PUT');await load();say('Profilo salvato. Le proposte precedenti vanno rigenerate se hai cambiato i dati.');});};
$('generate').onclick=()=>run(async()=>{if(!$('reviewExplanation')?.checked){say('Prima di generare, leggi la spiegazione e seleziona Ho letto.');$('overview').scrollIntoView({block:'start'});return;}state.plan=await api('/generate',{reviewed:true});renderPlan();say('Le idee sono pronte. Controlla ingredienti ed etichette prima di prepararle.');});
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){chosen=Number(b.dataset.day);renderPlan();}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('chatForm').elements.question.value=b.dataset.q;$('chatForm').elements.question.focus();});
$('chatForm').onsubmit=e=>{e.preventDefault();run(async()=>{const question=e.target.elements.question.value.trim();if(!pendingChat||pendingChat.question!==question)pendingChat={question,requestId:crypto.randomUUID()};const reply=await api('/chat',{...pendingChat,day:chosen,today:(new Date().getDay()+6)%7});pendingChat=null;if(reply.profileUpdated){state.profile=reply.profile;state.overview=reply.overview;renderOverview();if(reply.plan)state.plan=reply.plan;fillProfile();renderPlan();}bubble(question,'user');bubble(reply.answer,'assistant');if(reply.recalculationError)bubble(reply.recalculationError,'assistant');state.messages.push({role:'user',content:question},{role:'assistant',content:reply.answer});for(const m of reply.suggestions){const p=bubble(m.title+' · '+m.ingredients.map(k=>ingredients[k]||k).join(', '),'assistant');const details=document.createElement('p');details.textContent=m.preparation;p.append(details);const slot=document.createElement("select");slot.setAttribute("aria-label","Pasto da sostituire");const slots=m.type==="breakfast"?[[0,"Colazione"]]:m.type==="snack"?[[1,"Spuntino mattina"],[3,"Merenda"]]:[[2,"Pranzo"],[4,"Cena"]];for(const [value,label]of slots){const opt=document.createElement("option");opt.value=value;opt.textContent=label;slot.append(opt);}const apply=document.createElement("button");apply.type="button";apply.textContent="Usa questa idea per "+days[chosen];apply.onclick=()=>run(async()=>{state.plan=await api("/meal",{day:chosen,slot:Number(slot.value),menuId:m.id});renderPlan();say("Pasto aggiornato per "+days[chosen]+".");});p.append(slot,apply);}if(reply.profilePatch){const box=bubble('Modifica proposta: '+Object.entries(reply.profilePatch).map(([k,v])=>({weight:'Peso',goal:'Obiettivo',sport:'Sport'}[k])+': '+v).join(' · '),'assistant');const button=document.createElement('button');button.textContent='Conferma la modifica';button.type='button';button.onclick=()=>run(async()=>{await api('/profile',{...state.profile.profile,...reply.profilePatch},'PUT');button.disabled=true;await load();say('Profilo aggiornato. Rigenera le idee per tenerne conto.');});box.append(button);}e.target.reset();say('');$('messages').lastElementChild?.scrollIntoView({block:'nearest'});});};
$('olderMessages').onclick=()=>run(async()=>{const data=await api('/history?before='+encodeURIComponent(state.messages[0].created_at));state.messages=[...data.messages,...state.messages];renderMessages();if(data.messages.length<20)$('olderMessages').hidden=true;say('Conversazione precedente caricata.');});
$('deleteData').onclick=()=>{if(confirm('Cancellare definitivamente profilo, idee e conversazioni? L’account resterà attivo.'))run(async()=>{await api('/data',null,'DELETE');$('profileForm').reset();await load();say('Dati personali cancellati.');});};
async function init(){$('signupMode').hidden=C.registrationEnabled!==true;$('google').hidden=C.googleEnabled!==true;if(!configured()){say('Anteprima: accesso e AI verranno attivati dopo la configurazione dei servizi.');return;}const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('error_description')){say(hash.get('error_description'));history.replaceState(null,'',location.pathname);return;}if(hash.get('access_token')){saveSession({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_at:Date.now()/1000+Number(hash.get('expires_in')||3600)});const recovery=hash.get('type')==='recovery';history.replaceState(null,'',location.pathname);if(recovery){show('recovery');return;}}else try{session=JSON.parse(sessionStorage.getItem('alimenta-session'));}catch{}if(session)try{await load();}catch(e){say(e.message);}}
init();


